### ISSUE TITLE
Create new "Switch to most recently used tab" action

### ISSUE THREAD

**Issue by msramalho** [mikecrittenden/chrome-shortkeys#97] opened 2017-11-30 16:01 UTC
## Feature request 💪 
Instead of only going forward, there should be an action to navigate to the previous open tab, this would extremely useful as chrome has no option of doing it. This is a *Most Recently Used* navigation system and it is valuable for many users. 
[useful link on MRU in Notepad++](https://superuser.com/questions/591785/enabling-mru-tabbing-in-notepad-but-without-the-document-switcher-popup)

**Comment by mikecrittenden** [comment] 2017-11-30 16:37
One thought though - I think in most cases, this is implemented via a popup - hitting the key combo brings up the popup and as long as you keep holding "ctrl" (or whatever modifier it is) the popup stays open so you can keep cycling through them, until you take your finger off of ctrl. 

That implementation would be very difficult in Chrome - you can't easily create popups that appear on every tab and keep track of when the user releases ctrl to know when to stop cycling. So our options would be:

1) A single shortcut that just switches to the most recently used tab, one time, and hitting it again would go back to the tab you just came from (since THAT one is now the most recently used tab)
2) Maybe try to do something tricky like if you hit the key combo again within 5 seconds, then keep cycling through the original list, but if you wait 5 seconds before hitting it, then the list resets and you get taken back to the tab you came from.

**Comment by msramalho** [comment] 2017-11-30 16:59
Hey! I would go with **1.** first as it seems easier and already a big step towards it!

I don't think **e.** would be so hard, it's just a matter of counting how many times the user hits `tab` while holding `ctrl` and navigating over the FIFO of tabs.
This FIFO would be updated each time a new tab is entered.

**Comment by mikecrittenden** [comment] 2017-11-30 17:01
"just a matter of counting how many times the user hits tab while holding ctrl and navigating over the FIFO of tabs." as far as I can tell, that's either very difficult or impossible with Chrome's limitations on extensions unfortunately. We can see when the user hits ctrl+tab but I can't find a way to tell if the user hits tab again without releasing ctrl.

**Comment by msramalho** [comment] 2017-11-30 17:12
🤔 sad, so the `ctrl+tab` would have to be a simple navigation

**Comment by mikecrittenden** [comment] 2017-11-30 18:51
@msramalho actually, it looks like [this extension](https://chrome.google.com/webstore/detail/recent-tabs/ocllfmhjhfmogablefmibmjcodggknml/related?hl=en) does exactly what you're looking for. It has the option for just single tab switching and also supports the popup that lets you cycle through them. I just tested and it works great for me, and lets you choose custom keyboard shortcuts. 

I'm going to close this issue and just suggest using that extension.

**Closed by mikecrittenden** 2017-11-30 18:51 UTC
Labels: enhancement

**Comment by pmalecka** [comment] 2017-12-14 10:55
would it make sense to have an option for the next tab and previous tab actions - to traverse those tabs in MRU order? in that case - no special UI would be needed.

**Comment by mikecrittenden** [comment] 2017-12-14 14:22
@pmalecka the problem is that Shortkeys right now can't detect "hold down ctrl and press X repeatedly" for example, so there's no way to detect that the user is trying to cycle through the tabs. The best we could do without a big lift is to just switch back and forth between the previous tab and the current one when you hit the shortcut. It's not impossible to fully implement this feature to allow cycling though all of them, but then we'd just be re-inventing what https://chrome.google.com/webstore/detail/recent-tabs/ocllfmhjhfmogablefmibmjcodggknml/related?hl=en already does for Chrome, and what `browser.ctrlTab.previews` does in Firefox. Thoughts?

**Comment by pmalecka** [comment] 2017-12-16 10:27
Ok, say we only want to introduce an action that would allow the user to switch to a MRU tab. Not necessarily worrying about the Ctrl+Tab activation. Only one step backward would be allowed (essentialy emulating pressing Ctrl+tab once. This is what I believe is asked in the issue here https://github.com/pmalecka/chrome-shortkeys/issues/22#issuecomment-350404753

Without the UI indicating which tab are you actually going to switch to, it might be quite confusing for the user go forward/backward based on number of taps on the TAB key.

**Comment by getify** [comment] 2021-12-01 18:00
> Without the UI indicating which tab are you actually going to switch to, it might be quite confusing for the user go forward/backward based on number of taps on the TAB key.

I don't think that's what was being asked for. I think the "switch to MRU tab" would simply toggle... that is, you're currently on tab 3 but were previously on tab 7... when you click the shortcut key, you'd go from 3 back to 7... but now 3 is the MRU tab, so clicking the shortcut would go back to 3, then back to 7, then ... it just toggles, because each switch of tab changes the strictly-most-recently-used-tab. We don't need a stack of tab activations to go back through (like browser nav history), we just need "go back to where I just was".

FWIW, I've tried the other extension mentioned and I don't love it. I wish this extension would add this specific feature.
