### ISSUE TITLE
Does not detect form fields correctly

### ISSUE THREAD

**Issue by mystica555** [mikecrittenden/chrome-shortkeys#71] opened 2017-11-19 02:41 UTC
I have the shortcut "shift-rightarrow" and "shift-leftarrow" set to go forward and backward between tabs - just like it works in Konsole. 

However, even here in Github's bug report field, the shortcuts seem to still be enabled, instead of the assumed action of disabled-in-a-form. 

I re-saved preferences, after clicking the "enabled everywhere" option, and now amazingly other form fields work properly (understanding reloading the page re-injects the JS your extension creates, and I tested this on a different page as well where it started working only after re-saving). 

Is there some sort of bug in the reading/saving of preferences?  Perhaps something to do with the dropdown menu for where the option is enabled? 

Further, 'backspace' which I _also_ have set in your AddOn, and am NOT using Google's own "backspace to go back" addon, out of principle of using a better and more-featured option, has never accidentally browsed "back" in the current page history in the same tab, it literally deletes characters behind the insertion pointer as expected and always has.  Its the weirdness of shift-right/left that hasn't. 

So lets call this 'possible bug in the actioning on or reading of preferences'?

**Comment by mikecrittenden** [comment] 2017-11-19 03:04
So if I understand correctly, the shortcut was enabled in form fields even though that was initially unchecked, and it only became disabled after you went and checked the checkbox then unchecked it again?

**Comment by mystica555** [comment] 2017-11-19 04:25
This is mostly correct.

Prior to re-saving the changes, I had none of the dropdown 'websites' populated.  In the 'backspace' setting, I still don't.
![image](https://user-images.githubusercontent.com/4352219/32987350-26a46030-ccb7-11e7-9e88-0d2c2c74cd5f.png)
It looked like that, but was the other key combos/actions.

I only toggled the "active in form fields" for the shift-leftarrow combination, but decided to set the "all websites" option in both, like so:
![image](https://user-images.githubusercontent.com/4352219/32987357-792f9284-ccb7-11e7-8089-66ff6192df87.png) 
![image](https://user-images.githubusercontent.com/4352219/32987362-9adcdd7e-ccb7-11e7-8764-20ac54ec1487.png)

and re-saved.  Now I can highlight text even in the edit page of this bug form, whereas before I re-saved I could not.

**Comment by mystica555** [comment] 2017-11-20 02:17
I don't... 

I have precisely those 3 shortcuts; backspace, alt-leftarrow and alt-rightarrow and expect them to work the same everywhere, providing navigation outside of form fields, and text editing keys inside of form fields.

I literally expected them to work the same having 'no' populated 'websites' listed, and indeed 'backspace' works without having anything populated in that dropdown menu.  Once selected however, there is no way to remove the choice from the dropdown vs deleting and re-creating the shortcut and never selecting something in the first place.

**Comment by mikecrittenden** [comment] 2017-11-20 19:15
This is a bizarre one. I'm not sure what could have caused this. I'm going to leave it open to see if anyone else sees anything similar, but so far I've been unable to reproduce.

**Comment by mikecrittenden** [comment] 2017-11-28 15:35
Closing this for lack of info but feel free to reopen with more info.

**Closed by mikecrittenden** 2017-11-28 15:35 UTC
Labels: bug, needs more info
